apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-model
  namespace: default
spec:
  predictor:
    containers:
    - name: kserve-container
      image: churn-model-server:latest
      imagePullPolicy: IfNotPresent
      env:
      - name: MODEL_NAME
        value: "churn-predictor"
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: AWS_PROFILE
        value: "churn-dev"
